export const firebaseAuthErrorsAR = {
    "auth/claims-too-large" : "المطالبات كبيرة جدًا",
    "auth/email-already-exists" : "البريد الالكتروني موجود بالفعل",
    "auth/id-token-expired" : "انتهت صلاحية الرمز المميز للمعرف",
    "auth/id-token-revoked" : "تم إبطال رمز المعرف المميز",
    "auth/insufficient-permission" : "إذن غير كاف", 
    "auth/internal-error" : "خطأ داخلي",
    "auth/invalid-argument" : "سيطة غير صالحة",
    "auth/invalid-claims" : "مطالبات غير صالحة",
    "auth/invalid-continue-uri" : "uri تابع غير صالح", 
    "auth/invalid-creation-time" : "وقت إنشاء غير صالح",
    "auth/invalid-credential" : "شهادة اعتماد غير صالحة",
    "auth/invalid-disabled-field" : "حقل معطل غير صالح",
    "auth/invalid-display-name" : "اسم العرض غير صالح",
    "auth/invalid-dynamic-link-domain" : "مجال ارتباط ديناميكي غير صالح",
    "auth/invalid-email" : "بريد إلكتروني خاطئ", 
    "auth/invalid-email-verified" : "تم التحقق من بريد إلكتروني غير صالح",
    "auth/invalid-hash-algorithm" : "خوارزمية تجزئة غير صالحة",
    "auth/invalid-hash-block-size" : "حجم كتلة التجزئة غير صالح",
    "auth/invalid-hash-derived-key" : "مفتاح مشتق تجزئة غير صالح",
    "auth/invalid-hash-key" : "مفتاح تجزئة غير صالح",
    "auth/invalid-hash-memory-cost" : "تكلفة ذاكرة التجزئة غير الصالحة",
    "auth/invalid-hash-parallelization" : "موازاة التجزئة غير الصالحة",
    "auth/invalid-hash-rounds" : "جولات تجزئة غير صالحة",
    "auth/invalid-hash-salt-separator" : "فاصل ملح التجزئة غير صالح",
    "auth/invalid-id-token" : "رمز معرف غير صالح",
    "auth/invalid-last-sign-in" : "تسجيل الدخول الأخير غير صالح",
    "auth/invalid-page-token" : "رمز صفحة غير صالح",
    "auth/invalid-password" : "رمز مرور خاطئ", 
    "auth/invalid-password-hash" : "تجزئة كلمة المرور غير صالحة",
    "auth/invalid-password-salt" : "ملح كلمة المرور غير الصالحة",
    "auth/invalid-phone-number" : "رقم الهاتف غير صحيح",
    "auth/invalid-photo-url" : "عنوان url للصورة غير صالح",
    "auth/invalid-provider-data" : "بيانات الموفر غير صالحة",
    "auth/invalid-provider-id" : "معرف مزود غير صالح", 
    "auth/invalid-session-cookie-duration" : "مدة ملف تعريف ارتباط الجلسة غير صالحة",
    "auth/invalid-uid" : "معرف غير صالح", 
    "auth/invalid-user-import" : "استيراد مستخدم غير صالح",
    "auth/maximum-user-count-exceeded" : "تجاوز الحد الأقصى لعدد المستخدمين",
    "auth/missing-android-pkg-name" : "اسم ملف android pkg مفقود",
    "auth/missing-continue-uri" : "مفقود uri",
    "auth/missing-hash-algorithm" : "خوارزمية التجزئة المفقودة",
    "auth/missing-ios-bundle-id" : "معرف حزمة ios مفقود",
    "auth/missing-uid" : "uid مفقود",  
    "auth/operation-not-allowed" : "العملية غير مسموح بها",
    "auth/phone-number-already-exists" : "رقم الهاتف موجود بالفعل",
    "auth/project-not-found" : "المشروع غير موجود",
    "auth/reserved-claims" : "مطالبات محفوظة",  
    "auth/session-cookie-expired" : "انتهت صلاحية ملف تعريف ارتباط الجلسة",
    "auth/session-cookie-revoked" : "تم إبطال ملف تعريف ارتباط الجلسة",
    "auth/uid-already-exists" : "uid موجود بالفعل",
    "auth/unauthorized-continue-uri" : "تابع uri غير مصرح به",
    "auth/user-not-found" : "المستخدم ليس موجود"
};
