export const firebaseAuthErrorsAR: object = {
    "auth/claims-too-large" : "المطالبات كبيرة جدًا",
    "auth/email-already-exists" : "البريد الالكتروني موجود بالفعل",
    "auth/id-token-expired" : "انتهت صلاحية الرمز المميز للمعرف",
    "auth/id-token-revoked" : "تم إبطال رمز المعرف المميز",
    "auth/insufficient-permission" : "إذن غير كاف", 
    "auth/internal-error" : "خطأ داخلي",
    "auth/invalid-argument" : "سيطة غير صالحة",
    "auth/invalid-claims" : "مطالبات غير صالحة",
    "auth/invalid-continue-uri" : "uri تابع غير صالح", 
    "auth/invalid-creation-time" : "وقت إنشاء غير صالح",
    "auth/invalid-credential" : "شهادة اعتماد غير صالحة",
    "auth/invalid-disabled-field" : "حقل معطل غير صالح",
    "auth/invalid-display-name" : "اسم العرض غير صالح",
    "auth/invalid-dynamic-link-domain" : "مجال ارتباط ديناميكي غير صالح",
    "auth/invalid-email" : "بريد إلكتروني خاطئ", 
    "auth/invalid-email-verified" : "تم التحقق من بريد إلكتروني غير صالح",
    "auth/invalid-hash-algorithm" : "خوارزمية تجزئة غير صالحة",
    "auth/invalid-hash-block-size" : "حجم كتلة التجزئة غير صالح",
    "auth/invalid-hash-derived-key" : "مفتاح مشتق تجزئة غير صالح",
    "auth/invalid-hash-key" : "مفتاح تجزئة غير صالح",
    "auth/invalid-hash-memory-cost" : "تكلفة ذاكرة التجزئة غير الصالحة",
    "auth/invalid-hash-parallelization" : "موازاة التجزئة غير الصالحة",
    "auth/invalid-hash-rounds" : "جولات تجزئة غير صالحة",
    "auth/invalid-hash-salt-separator" : "فاصل ملح التجزئة غير صالح",
    "auth/invalid-id-token" : "رمز معرف غير صالح",
    "auth/invalid-last-sign-in" : "تسجيل الدخول الأخير غير صالح",
    "auth/invalid-page-token" : "رمز صفحة غير صالح",
    "auth/invalid-password" : "رمز مرور خاطئ", 
    "auth/invalid-password-hash" : "تجزئة كلمة المرور غير صالحة",
    "auth/invalid-password-salt" : "ملح كلمة المرور غير الصالحة",
    "auth/invalid-phone-number" : "رقم الهاتف غير صحيح",
    "auth/invalid-photo-url" : "عنوان url للصورة غير صالح",
    "auth/invalid-provider-data" : "بيانات الموفر غير صالحة",
    "auth/invalid-provider-id" : "معرف مزود غير صالح", 
    "auth/invalid-session-cookie-duration" : "مدة ملف تعريف ارتباط الجلسة غير صالحة",
    "auth/invalid-uid" : "معرف غير صالح", 
    "auth/invalid-user-import" : "استيراد مستخدم غير صالح",
    "auth/maximum-user-count-exceeded" : "تجاوز الحد الأقصى لعدد المستخدمين",
    "auth/missing-android-pkg-name" : "اسم ملف android pkg مفقود",
    "auth/missing-continue-uri" : "مفقود uri",
    "auth/missing-hash-algorithm" : "خوارزمية التجزئة المفقودة",
    "auth/missing-ios-bundle-id" : "معرف حزمة ios مفقود",
    "auth/missing-uid" : "uid مفقود",  
    "auth/operation-not-allowed" : "العملية غير مسموح بها",
    "auth/phone-number-already-exists" : "رقم الهاتف موجود بالفعل",
    "auth/project-not-found" : "المشروع غير موجود",
    "auth/reserved-claims" : "مطالبات محفوظة",  
    "auth/session-cookie-expired" : "انتهت صلاحية ملف تعريف ارتباط الجلسة",
    "auth/session-cookie-revoked" : "تم إبطال ملف تعريف ارتباط الجلسة",
    "auth/uid-already-exists" : "uid موجود بالفعل",
    "auth/unauthorized-continue-uri" : "تابع uri غير مصرح به",
    "auth/user-not-found" : "المستخدم ليس موجود"
};

export const firebaseAuthErrorsFR: object = {
    "auth/claims-too-large" : "les réclamations sont trop importantes",
    "auth/email-already-exists" : "l'email existe déjà",
    "auth/id-token-expired" : "Le jeton d'identité a expiré",
    "auth/id-token-revoked" : "Le jeton d'identité a été révoqué",
    "auth/insufficient-permission" : "permission insuffisante", 
    "auth/internal-error" : "erreur interne",
    "auth/invalid-argument" : "argument invalide",
    "auth/invalid-claims" : "revendications invalides",
    "auth/invalid-continue-uri" : "non valide continue uri", 
    "auth/invalid-creation-time" : "heure de création invalide",
    "auth/invalid-credential" : "accréditation non valide",
    "auth/invalid-disabled-field" : "champ désactivé invalide",
    "auth/invalid-display-name" : "nom d'affichage invalide",
    "auth/invalid-dynamic-link-domain" : "domaine de lien dynamique non valide",
    "auth/invalid-email" : "email invalide", 
    "auth/invalid-email-verified" : "email invalide vérifié",
    "auth/invalid-hash-algorithm" : "algorithme de hachage invalide",
    "auth/invalid-hash-block-size" : "taille de bloc de hachage non valide",
    "auth/invalid-hash-derived-key" : "clé dérivée de hachage non valide",
    "auth/invalid-hash-key" : "clé de hachage invalide",
    "auth/invalid-hash-memory-cost" : "coût de la mémoire de hachage non valide",
    "auth/invalid-hash-parallelization" : "parallélisation de hachage non valide",
    "auth/invalid-hash-rounds" : "rounds de hachage invalides",
    "auth/invalid-hash-salt-separator" : "séparateur de sel de hachage invalide",
    "auth/invalid-id-token" : "jeton d'identification invalide",
    "auth/invalid-last-sign-in" : "dernière connexion invalide",
    "auth/invalid-page-token" : "jeton de page non valide",
    "auth/invalid-password" : "Mot de passe incorrect", 
    "auth/invalid-password-hash" : "hachage de mot de passe invalide",
    "auth/invalid-password-salt" : "sel de mot de passe invalide",
    "auth/invalid-phone-number" : "Numéro de téléphone invalide",
    "auth/invalid-photo-url" : "URL de la photo invalide",
    "auth/invalid-provider-data" : "données de fournisseur non valides",
    "auth/invalid-provider-id" : "identifiant de fournisseur invalide", 
    "auth/invalid-session-cookie-duration" : "durée de cookie de session non valide",
    "auth/invalid-uid" : "uid invalide", 
    "auth/invalid-user-import" : "importation d'utilisateurs non valide",
    "auth/maximum-user-count-exceeded" : "nombre maximal d'utilisateurs dépassé",
    "auth/missing-android-pkg-name" : "nom du package Android manquant",
    "auth/missing-continue-uri" : "manquant continuer uri",
    "auth/missing-hash-algorithm" : "algorithme de hachage manquant",
    "auth/missing-ios-bundle-id" : "ID de bundle iOS manquant",
    "auth/missing-uid" : "uid manquant",  
    "auth/operation-not-allowed" : "opération non autorisée",
    "auth/phone-number-already-exists" : "le numéro de téléphone existe déjà",
    "auth/project-not-found" : "projet non trouvé",
    "auth/reserved-claims" : "revendications réservées",  
    "auth/session-cookie-expired" : "cookie de session expiré",
    "auth/session-cookie-revoked" : "cookie de session révoqué",
    "auth/uid-already-exists" : "uid existe déjà",
    "auth/unauthorized-continue-uri" : "continue uri non autorisée",
    "auth/user-not-found" : "utilisateur non trouvé"
};
